PSPCommerce/Models/Product.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PSPCommerce.Models
{
    public class Product : BaseModel
    {
        [Required]
        public string Name { get; set; }
        public List<ProductImage> Images { get; set; } = new List<ProductImage>();
        [Required]
        public int Price { get; set; }
        public int CategoryID { get; set; }
        public Category? _Category { get; set; } = null!;

        [Required]
        public string Description { get; set; }
    }
}

PSPCommerce/Controllers/FavoriteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSPCommerce.Data;
using PSPCommerce.Models;

namespace PSPCommerce.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public FavoriteController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Favorite
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var applicationDbContext = _context.Favorite.Where(fav => fav.UserID == user.Id).Include(f => f._Product).ThenInclude(c => c.Images).Include(f => f._User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Favorite/Details/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Favorite == null)
            {
                return NotFound();
            }

            var favorites = await _context.Favorite
                .Include(f => f._Product)
                .Include(f => f._User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (favorites == null)
            {
                return NotFound();
            }

            return View(favorites);
        }

        // GET: Favorite/Create
        [Authorize(Roles = "Admin")]

        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Product, "ID", "Description");
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id");
            return View();
        }

        // POST: Favorite/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Create([Bind("ProductID,UserID,ID")] Favorites favorites)
        {
            if (ModelState.IsValid)
            {
                _context.Add(favorites);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ID", "Description", favorites.ProductID);
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", favorites.UserID);
            return View(favorites);
        }

        [HttpPost("/favorite/add")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Add(int productId)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return RedirectToPage("/Account/Login", new { area = "Identity" });
            }

            var userId = user.Id;
            var favorites = await _context.Favorite.FirstOrDefaultAsync(ci => ci.UserID == userId && ci.ProductID == productId);

            if (favorites == null)
            {
                favorites = new Favorites
                {
                    ProductID = productId,
                    UserID = userId,
                };

                await _context.Favorite.AddAsync(favorites);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: Favorite/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Favorite == null)
            {
                return NotFound();
            }

            var favorites = await _context.Favorite.FindAsync(id);
            if (favorites == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ID", "Description", favorites.ProductID);
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", favorites.UserID);
            return View(favorites);
        }

        // POST: Favorite/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int id, [Bind("ProductID,UserID,ID")] Favorites favorites)
        {
            if (id != favorites.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favorites);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoritesExists(favorites.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Product, "ID", "Description", favorites.ProductID);
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", favorites.UserID);
            return View(favorites);
        }

        // GET: Favorite/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Favorite == null)
            {
                return NotFound();
            }

            var favorites = await _context.Favorite
                .Include(f => f._Product)
                .Include(f => f._User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (favorites == null)
            {
                return NotFound();
            }

            return View(favorites);
        }

        // POST: Favorite/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Favorite == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Favorite'  is null.");
            }
            var favorites = await _context.Favorite.FindAsync(id);
            if (favorites != null)
            {
                _context.Favorite.Remove(favorites);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoritesExists(int id)
        {
            return (_context.Favorite?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

PSPCommerce/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSPCommerce.Data;
using PSPCommerce.Models;

namespace PSPCommerce.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: product
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Product.Include(p => p._Category).Include(c => c.Images)
;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p._Category)
                .Include(c => c.Images)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: product/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name");
            return View();
        }

        private async Task<List<ProductImage>> StoreAndGetImages(List<IFormFile> imageFiles)
        {
            List<ProductImage> images = new List<ProductImage>();
            if (imageFiles != null && imageFiles.Count > 0)
            {
                foreach (var imageFile in imageFiles)
                {
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        var fileName = Path.GetRandomFileName().Replace(".", string.Empty);
                        var fileExtension = Path.GetExtension(imageFile.FileName);
                        var uniqueFileName = fileName + fileExtension;

                        // Save the image to a specific location
                        var imagePath = Path.Combine("wwwroot/images", uniqueFileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await imageFile.CopyToAsync(stream);
                        }

                        var imageUrl = Path.Combine("images", uniqueFileName);
                        images.Add(new ProductImage { ImageUrl = imageUrl });
                    }
                }
            }
            return images;
        }

        // POST: product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name,Price,CategoryID,Description,ID")] Product product, List<IFormFile> imageFiles)
        {
            // log model state errors
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            if (ModelState.IsValid)
            {
                StoreAndGetImages(imageFiles).ContinueWith((images) =>
                {
                    product.Images = images.Result;
                }).Wait();

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }


        [HttpGet]
        [Route("product/search")]
        public async Task<IActionResult> Search([FromQuery] ProductSearchParamsDto query)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            ViewBag.Page = query.Page;
            ViewBag.PageSize = query.PageSize;
            var q = (query.Q ?? String.Empty).ToLower();
            ViewBag.Q = q;
            ViewBag.Category = query.Category;

            ViewBag.MinPrice = query.minPrice;
            ViewBag.MaxPrice = query.maxPrice;

            var products = _context.Product.Where(p => p.Name.ToLower().Contains(q) || p.Description.ToLower().Contains(q))
                .Where(p => p.Price >= query.minPrice && p.Price <= query.maxPrice);

            if (query.Category != null)
            {
                products = products.Where(p => p.CategoryID == query.Category).Include(p => p._Category);
            }

            var paginatedProducts = await products.Include(c => c.Images).Skip((query.Page - 1) * query.PageSize)
                .Take(query.PageSize)
                .ToListAsync();

            ViewBag.TotalPages = Math.Ceiling((double)products.Count() / query.PageSize);

            ViewBag.CategoryID = new SelectList(_context.Category, "ID", "Name");
            return View(paginatedProducts);
        }

        // GET: product/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(p => p.Images).FirstOrDefaultAsync(p => p.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int id, [Bind("Name,Price,CategoryID,Description,ID")] Product product, List<IFormFile> imageFiles)
        {
            // loop imageFiles
            foreach (IFormFile item in imageFiles)
            {
                Console.WriteLine("HERE", item, "SAD");

            }
            // log model state errors
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }
            if (id != product.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var images = await StoreAndGetImages(imageFiles);
                    foreach (ProductImage img in images)
                    {
                        product.Images.Add(img);
                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: product/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p._Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return (_context.Product?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

PSPCommerce/Views/Product/Create.cshtml
@model PSPCommerce.Models.Product

@{
    ViewData["Title"] = "Create Product";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" })) {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" required/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                Produt Images
                <input type="file" name="imageFiles" class="form-control" required multiple/>
                <span class="text-danger">@Html.ValidationMessage("imageFiles")</span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" value="100" required/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID" required></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSPCommerce/Views/Product/Delete.cshtml
@model PSPCommerce.Models.Product

@{
    ViewData["Title"] = "Delete Product";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd> *@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model._Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model._Category.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PSPCommerce/Views/Product/Details.cshtml
@model PSPCommerce.Models.Product

@{
    ViewData["Title"] = Model.Name;
}

<div class="row p-3 shadow rounded">
  <div class="col-sm-12 col-md-8 col-lg-5 g-3 d-flex">
    <div>
      @foreach (var image in Model.Images)
      {
        @* <div class="col-md-4"> *@
        <img class="image-small me-2" src="/@image.ImageUrl" alt="@Model.Name" style="display:block" onclick="changeImage('@image.ImageUrl')"/>
          @* </div> *@
      }
    </div>
    <div class="main-image-container">
      <img class="image me-2" id="main-image" src="/@Model.Images[0].ImageUrl" alt="@Model.Name" />
    </div>
  </div>
  

  <div id="cart-text" class="col-sm-12 col-md-4 col-lg-7 g-3">
    <button class="free-shipping">Free shipping</button>
    <h2>@Model.Name</h2>
    <h4>@Model.Description</h4>
    <h1>Rs. @Model.Price</h1>

    <div class="row gap-2">
      <div class="col-sm-12 col-lg-6">
        <form asp-controller="Cart" asp-action="Add" method="post">
            <input type="hidden" value="@Model.ID" name="productId" />
            <button type="submit" value="Add to Cart" class="add-to-cart">Add to Cart</button>
        </form>
        <form asp-controller="Favorite" asp-action="Add" method="post">
            <input type="hidden" value="@Model.ID" name="productId" />
            <button type="submit" value="Add to Favorites" class="add-to-cart">Add to Favorites</button>
        </form>
      </div>
    </div>
</div>

  </div>
</div>

<script>
  const mainImage = document.getElementById("main-image");
  const changeImage = (url) => {
    mainImage.src =  new URL(url,location.origin).pathname
  }

</script>
    
<style>
.image {
  height: 20rem;
}

.image-small {
  height: 4.9rem;
  margin-bottom: 5px;
  border-radius: 0.4rem;
}

.image-small:hover {
  background-color: gray;
  opacity: 0.7;
}

.main-image-container {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100%;
}

  @* #cart-text {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: flex-start;
  } *@

.free-shipping {
  font-family: "Lato", sans-serif;
  color: #fff;
  font-size: 0.65rem;
  background-color: #191649;
  border: 0;
  border-radius: 0.9rem;
  padding: 0.3rem 0.4rem;
  margin-bottom: 0.5rem;
}

h2 {
  font-family: "Lato", sans-serif;
  font-size: 1.2rem;
  font-weight: 700;
  line-height: 1.5rem;
  margin-bottom: 2rem;
  cursor:default;
}

h3 {
  font-family: "Lato", sans-serif;
  font-weight: 300;
  font-size: 0.65rem;
  text-decoration: line-through;
  cursor:default;
}

h1 {
  font-family: "Lato", sans-serif;
  font-weight: 900;
  cursor:default;
  font-size: 2.5rem;
}

h4 {
  font-family: "Lato", sans-serif;
  font-weight: 300;
  font-size: 0.7rem;
  margin-bottom: 1rem;
  cursor:default;
}

.add-to-cart {
  width: 100%;
  height: 2.7rem;
  font-family: "Lato", sans-serif;
  font-size: 1rem;
  background-color: #4787e9;
  color: #fff;
  font-weight: 400;
  border: 0;
  border-bottom: 0.3rem solid #1e56ed;
  border-radius: 0.4rem;
  margin-bottom: 1rem;
  cursor: pointer;
  padding: 0 1rem;
}

.add-to-cart:active {
  border-bottom: 0;
}

.stock {
  font-weight: 700;
  text-decoration: none;
  margin-bottom: 2rem;
}

h3 i {
  color: #04d58b;
  margin-right: 0.2rem;
}

#buttons {
  display: flex;
  justify-content: space-between;
  gap: 1rem;
}

.form {
  display: inline-block;
}
</style>

PSPCommerce/Views/Product/Edit.cshtml
@model PSPCommerce.Models.Product

@{
    ViewData["Title"] = "Edit Product";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" })) {
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                Add Product Images
                <input type="file" name="imageFiles" class="form-control" required multiple/>
                <span class="text-danger">@Html.ValidationMessage("imageFiles")</span>
                <div class="images">
                    @foreach (var image in Model.Images)
                    {
                        <div class="img-small-container">
                            <img class="img-small" src="/@image.ImageUrl" alt="image">
                            <a class="cross" asp-controller="ProductImage" asp-action="DeleteImage" asp-route-id="@image.ID">
                                ❌
                            </a>
                        </div>
                    }
                </div>
                @* <span asp-validation-for="ImageUrl" class="text-danger"></span> *@
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<style>
    .images {
        display: flex;
        gap: 5px;
        flex-wrap: wrap;
        margin: 1rem 0;
    }
    .img-small-container {
        position: relative;    
        width: 6rem;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .img-small-container a {
        text-decoration: none;
    }
    .img-small {
        height: 6rem;
    }

    .cross {
        position: absolute;
        top: 0;
        right: 0;
        cursor: pointer;
    }
    .cross:hover {
        scale: 1.2;
    }
</style>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSPCommerce/Views/Product/Index.cshtml
@model IEnumerable<PSPCommerce.Models.Product>

@{
    ViewData["Title"] = "Products";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model._Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
@foreach (var item in Model) {
    
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ImageUrl)*@
                <img src="@item.Images[0].ImageUrl" alt="@item.Description" height="100" width="100"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>