PSPCommerce/Controllers/AdminOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSPCommerce.Data;
using PSPCommerce.Models;

namespace PSPCommerce.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminOrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminOrderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminOrder
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Order.Include(o => o._User).Include(o => o._OrderItems).ThenInclude(oi => oi._Product).ThenInclude(p => p.Images);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: AdminOrder/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o._User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: AdminOrder/Create
        public IActionResult Create()
        {
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id");
            return View();
        }

        // POST: AdminOrder/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserID,TotalPrice,PaymentIntentID,IsPaid,ID,CreatedAt")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", order.UserID);
            return View(order);
        }

        // GET: AdminOrder/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", order.UserID);
            return View(order);
        }

        // POST: AdminOrder/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserID,TotalPrice,PaymentIntentID,IsPaid,ID,CreatedAt")] Order order)
        {
            if (id != order.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserID"] = new SelectList(_context.User, "Id", "Id", order.UserID);
            return View(order);
        }

        // GET: AdminOrder/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .Include(o => o._User)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: AdminOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                _context.Order.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return (_context.Order?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

PSPCommerce/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PSPCommerce.Data;
using PSPCommerce.Models;

namespace PSPCommerce.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: product
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Product.Include(p => p._Category).Include(c => c.Images)
;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p._Category)
                .Include(c => c.Images)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: product/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name");
            return View();
        }

        private async Task<List<ProductImage>> StoreAndGetImages(List<IFormFile> imageFiles)
        {
            List<ProductImage> images = new List<ProductImage>();
            if (imageFiles != null && imageFiles.Count > 0)
            {
                foreach (var imageFile in imageFiles)
                {
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        var fileName = Path.GetRandomFileName().Replace(".", string.Empty);
                        var fileExtension = Path.GetExtension(imageFile.FileName);
                        var uniqueFileName = fileName + fileExtension;

                        // Save the image to a specific location
                        var imagePath = Path.Combine("wwwroot/images", uniqueFileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await imageFile.CopyToAsync(stream);
                        }

                        var imageUrl = Path.Combine("images", uniqueFileName);
                        images.Add(new ProductImage { ImageUrl = imageUrl });
                    }
                }
            }
            return images;
        }

        // POST: product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("Name,Price,CategoryID,Description,ID")] Product product, List<IFormFile> imageFiles)
        {
            // log model state errors
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            if (ModelState.IsValid)
            {
                StoreAndGetImages(imageFiles).ContinueWith((images) =>
                {
                    product.Images = images.Result;
                }).Wait();

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }


        [HttpGet]
        [Route("product/search")]
        public async Task<IActionResult> Search([FromQuery] ProductSearchParamsDto query)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            ViewBag.Page = query.Page;
            ViewBag.PageSize = query.PageSize;
            var q = (query.Q ?? String.Empty).ToLower();
            ViewBag.Q = q;
            ViewBag.Category = query.Category;

            ViewBag.MinPrice = query.minPrice;
            ViewBag.MaxPrice = query.maxPrice;

            var products = _context.Product.Where(p => p.Name.ToLower().Contains(q) || p.Description.ToLower().Contains(q))
                .Where(p => p.Price >= query.minPrice && p.Price <= query.maxPrice);

            if (query.Category != null)
            {
                products = products.Where(p => p.CategoryID == query.Category).Include(p => p._Category);
            }

            var paginatedProducts = await products.Include(c => c.Images).Skip((query.Page - 1) * query.PageSize)
                .Take(query.PageSize)
                .ToListAsync();

            ViewBag.TotalPages = Math.Ceiling((double)products.Count() / query.PageSize);

            ViewBag.CategoryID = new SelectList(_context.Category, "ID", "Name");
            return View(paginatedProducts);
        }

        // GET: product/Edit/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product.Include(p => p.Images).FirstOrDefaultAsync(p => p.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Edit(int id, [Bind("Name,Price,CategoryID,Description,ID")] Product product, List<IFormFile> imageFiles)
        {
            // loop imageFiles
            foreach (IFormFile item in imageFiles)
            {
                Console.WriteLine("HERE", item, "SAD");

            }
            // log model state errors
            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }
            if (id != product.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var images = await StoreAndGetImages(imageFiles);
                    foreach (ProductImage img in images)
                    {
                        product.Images.Add(img);
                    }
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Category, "ID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: product/Delete/5
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Product == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p._Category)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Product == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Product'  is null.");
            }
            var product = await _context.Product.FindAsync(id);
            if (product != null)
            {
                _context.Product.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return (_context.Product?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

PSPCommerce/Views/AdminOrder/Create.cshtml
@model PSPCommerce.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class ="form-control" asp-items="ViewBag.UserID"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentIntentID" class="control-label"></label>
                <input asp-for="PaymentIntentID" class="form-control" />
                <span asp-validation-for="PaymentIntentID" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPaid" /> @Html.DisplayNameFor(model => model.IsPaid)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSPCommerce/Views/AdminOrder/Delete.cshtml
@model PSPCommerce.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentIntentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentIntentID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPaid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model._User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model._User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PSPCommerce/Views/AdminOrder/Details.cshtml
@model PSPCommerce.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentIntentID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentIntentID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsPaid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsPaid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model._User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model._User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PSPCommerce/Views/AdminOrder/Edit.cshtml
@model PSPCommerce.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserID" class="control-label"></label>
                <select asp-for="UserID" class="form-control" asp-items="ViewBag.UserID"></select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentIntentID" class="control-label"></label>
                <input asp-for="PaymentIntentID" class="form-control" />
                <span asp-validation-for="PaymentIntentID" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPaid" /> @Html.DisplayNameFor(model => model.IsPaid)
                </label>
            </div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PSPCommerce/Views/AdminOrder/Index.cshtml
@model IEnumerable<PSPCommerce.Models.Order>

@{
    ViewData["Title"] = "Orders";
}

<link rel="stylesheet" href="~/css/order.css" />

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


@foreach (var order in Model) {
    <a asp-controller="AdminOrder" asp-action="Details" asp-route-id="@order.ID">
    <div class="order">
        <div class="top">
            <div>
                Order #@order.ID
                <div>By @order._User.Email | PaymentID: @order.PaymentIntentID</div>
                <div class="text-secondary">Placed on @order.CreatedAt.ToString("d' 'MMMM' 'yyyy")</div>
            </div>
            <div>
                @if (@order.IsPaid)
                {
                    <span class="text-success">Paid</span>
                } else {
                    <span class="text-danger">Payment Pending</span>
                }
            </div>
        </div>
        <div class="main">
            @foreach (var item in order._OrderItems)
            {
                <a asp-controller="Product" asp-action="Details" asp-route-id="@item._Product.ID">
                    <div class="order-item">
                        <div>
                            <img src="/@item._Product.Images[0].ImageUrl" alt="@item._Product.Name" />
                        </div>
                        <div class="product">
                            @item._Product.Name
                        </div>
                        <div class="quantity">Qty: @item.Quantity</div>
                        <div>
                            Price:
                            <div>Rs.@(item._Product.Price * item.Quantity)</div>
                        </div>
                    </div>
                </a>
            }
            <div class="d-flex justify-content-between">
                <div class="total">
                    <div>Total</div>
                    <div>Rs.@order.TotalPrice</div>
                </div>
                <div>
                    <a asp-action="Edit" asp-route-id="@order.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@order.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@order.ID">Delete</a>
                </div>
            </div>
        </div>
    </div>
    </a>
}